// import { createGlobalState } from "react-hooks-global-state";
// const { setGlobalState, useGlobalState } = createGlobalState({
//     thumbtake: 10,
//     thumbskip: 0,
//     relatedtake: 10,
//     relatedskip: 0,
//     editingMode: false,
//     urlData: 0,
//     managementUrlData: "",
//     rowNumber: 0,
//     setInitSlice: 1,
//     fromDate: null,
//     toDate: null,
//     ItemPerpage: "10",
//     AgentPerpage: "Select Email Address",
//     SelectedReciever:"",
//     setItemID: 0,
//     message: "",
//     useEmail: "",
//     useLevel: "",
//     Management: [],
//     cookieEmailAddress: "",
//     cookieUserLevel: "",
//     cookieActiveUser: "",
//     messageCount:[],
//     cookieArray:{
//         accountEmail:""
//     },
//     thumbnailSearch: "",
//     thumbnailData: null,
//     thumbnailCategory: "",
//     thumbnailProductTypes: "",
//     thumbnailCollectionItems:"",
//     thumbnailDiscounted:"",
//     thumbnailNewData:"",
//     descAsc: null,
//     activeModel: "/honda_pcx.glb",
//     saveDeviceid: "",
//     drawer:true,
//     checkoutAddress:"",
//     checkoutContact:"",
//     CurrentOrderStage:"",
//     CurrentPage:1,
//     sortDirection:'asc',
//     sortBy:'price'
// });
// export { useGlobalState, setGlobalState };
